[".local/share/antidote"]
type = "git-repo"
url = "https://github.com/mattmc3/antidote.git"
refreshPeriod = "168h"

[".config/tmux/plugins/tpm"]
type = "git-repo"
url = "https://github.com/tmux-plugins/tpm.git"
refreshPeriod = "168h"

[".config/ranger/plugins/ranger_devicons"]
type = "git-repo"
url = "https://github.com/alexanderjeurissen/ranger_devicons"
refreshPeriod = "168h"

[".local/share/zsh/kubectl_aliases.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/ahmetb/kubectl-aliases/master/.kubectl_aliases"
refreshPeriod = "168h"

[".config/ghostty/themes/catppuccin-mocha"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/ghostty/refs/heads/main/themes/catppuccin-mocha.conf"
refreshPeriod = "168h"

[".config/ghostty/shaders"]
type = "git-repo"
url = "https://github.com/sahaj-b/ghostty-cursor-shaders"
refreshPeriod = "168h"
