gui:
  showFileTree: false
git:
  log:
    showGraph: "always"
    showWholeGraph: true
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  # branchLogCmd: "git log --color=always --decorate --oneline --graph --stat"
  branchLogCmd: git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium --stat {{branchName}} --
  allBranchesLogCmds:
    - git log --graph --all --color=always --abbrev-commit --decorate --date=relative  --pretty=medium
os:
  # editPreset: 'nvim'
  edit: "NVIM_APPNAME=lazyvim nvim"
quitOnTopLevelReturn: true
keybinding:
  universal:
    nextScreenMode: "="
    prevScreenMode: "-"
    prevBlock-alt: "K"
    nextBlock-alt: "J"
    nextTab: "l"
    prevTab: "h"
    # scrollLeft: 'h'
    # scrollRight: 'l'
    copyToClipboard: "y"
  commits:
    # renameCommit: "g"
    # renameCommitWithEditor: "R"
    # viewResetOptions: "r"
    copyCommitAttributeToClipboard: "Y"
  branches:
    checkoutPreviousBranch: ""
